# Site Settings
title: Xiaofeng Mao
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: 毛潇锋
tagline: Postgraduate Student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'My research interest focuses on domain adaptation (transfer learning) and object tracking in computer vision. Currently, I am working on themal infrared object tracking problem and prepare for an international conference submitting next year. I also focus on cutting-edge research in the field of image synthesis, including generative adversarial networks (GANs) and image style transfer. More research details, please refer to <a href="https://www.zhihu.com/people/mao-xiao-feng-29-7/activities">My Zhihu Link</a>.'

#sidebar links
email: hzmaoxiaofeng@163.com
phone: 188 0462 1729
website: blog.csdn.net/mao_xiao_feng #do not add http://
github: github.com/xfmao
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
